routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('cadastrar', 'RegistrationController@cadastrar');
Route::post('cadastrar', 'RegistrationController@postRegister');

Route::get('entrar', 'SessionsController@login');
Route::post('entrar', 'SessionsController@postLogin');
Route::get('logout', 'SessionsController@logout')->name('logout');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::resource('contato', 'ContatoController');
    Route::get('contatos', 'CadastradoController@contatos')->name('contatos');

    

    //categoria
    Route::get('categoria', 'CategoryController@index');
    Route::get('contatos/{categoria}', 'CategoryController@contatosCategoria')->name('pesquisaCategoria');
    // lixeira
    Route::get('lixeira', 'ContatoController@trash')->name('lixeira');
    Route::post('restore/{contato}', 'ContatoController@restore')->name('restore');
    Route::post('exclui/{contato}', 'ContatoController@forceDestroy')->name('exclui');

    // Routes de botoes delete(-) em edit
    Route::delete('delete/tel/{id}', 'TelController@deleteTel');
    Route::delete('delete/email/{id}', 'EmailController@deleteEmail');
    Route::delete('delete/categoria/{id}/{contato}', 'CategoryController@deleteCategory');
    Route::delete('delete/endereco/{id}', 'AddressController@deleteAddress');

    Route::post('restoreAll', 'ContatoController@restoreAll');
    Route::get('/', 'ContatoController@index');

    Route::get('events', 'EventController@index')->name('events.index');
    Route::resource('events', 'EventController');
    // Route::get('events/list', 'EventController@listEvent')->name('events.list');
    // Route::delete('event/{eventId}', 'EventController@deleteEvent')->name('events.delete');

    Route::get('contact/import/google', ['as' => 'google.import', 'uses' => 'ContatoController@importGoogleContact']);
    Route::post('contatos/google', 'ContatoController@importadosGoogle');
    Route::get('excel', 'ContatoController@excel');
    Route::get('contacts/export/', 'ContatoController@export');

    Route::get('/search', 'SearchController@search');
});

Route::get('terms', function () {
    return view('termos.terms');
});

Route::get('terms2', function () {
    return view('termos.terms2');
});

Route::get('primeira', function () {
    return view('paginas.primeira');
});

Route::get('teste', function () {
    return view('auth.teste');
});


// background-size:cover;

resources/views/paginas/categoria.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
  @include('flash')
  <h4>
    Categorias:
  </h4>
  <div class="row">

    @foreach($categorias as $categoria)
    <div class="col-md-3 text-center" style="padding-top: 20px;">
      <a type="button" class="btn btn-primary rounded" href="contatos/{{$categoria->category}}">{{$categoria->category}}</a>
    </div>

    @endforeach
  </div>
</div>
@stop

resources/views/paginas/contatos.blade.php
@extends('layouts.app')


@section('content')



<div class="col-12 container-fluid ">
    <div class="row">
        
        <div class="col-12 col-sm-12 table-responsive "style="overflow-x:auto;">
            {!! csrf_field() !!}
            @include('flash')
            <h1 class="rounded-top " style="background: #054a459e;padding: 
                    2px;margin-bottom: 0px;margin-top: 10px; color:#000000;">
                    Contatos:
                <a type="button" class="btn btn-success rounded"  href="contact/import/google">IMPORTAR DO GOOGLE</a>                
                <a type="button" class="btn btn-warning rounded"  href="excel">EXPORTAR</a>
            </h1>
            
            <table class="table table-bordered table-striped ">
                <thead class="thead-dark">
                    <tr>
                        <th class="textCenter">
                            Nome:
                        </th>
                        <th class="textCenter">
                            Telefone:
                        </th>
                        <th class="textCenter">
                            Excluir:
                        </th>
                    </tr>
                </thead>
                @foreach($contacts as $contact)
                <tbody class="background-contatos">
                    <tr class="btnDelete" id="{{$contact->id}}" data-id="{{$contact->id}}">
                        <td class="textCenter">
                            <a class="nav-link contato-link link-contato" href="contato/{{$contact->id}}/edit">
                                <p>{{ $contact->name }}
                                    <span style="font-size: 14px"> {{ $contact->last_name }}</span>
                                </p>
                            </a>
                        </td>
                        <td class="textCenter" name="tel" style="font-size: 22px;">
                            @if(is_null($contact->tels->first()))
                            ----
                            @else
                                @if($contact->tels->first()->tel!='xxxx')                                
                                <div class="masktelcontatos">
                                    {{ $contact->tels->first()->tel}}
                                </div>
                                @else
                                    {{ $contact->tels->first()->tel}}
                                @endif
                            @endif
                        </td>

                        <td class="textCenter">
                            <!-- <button class="btn btn-danger delete-contact" value="{{$contact->id}}">Deletar</button>  -->
                            <button type="button" class="btn btn-danger-tabela btnDelete" data-toggle="modal" data-id="" data-target="#myModal">Delete</button>
                        </td>

                    </tr>
                </tbody>
                @endforeach
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Deletar?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                tem certeza que deseja enviar contato para lixeira?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <!-- <button class="btn btn-danger delete-contact" value="">Deletar</button>  -->
                                <button type="button" class="btn btn-danger delete-contact" value="" id="delete-btn">Deletar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </table>
            
        </div>
    </div>
</div>
<!-- </div> -->


@stop

resources/views/paginas/contatosImportados.blade.php
@extends('layouts.app')


@section('content')

<div class="container-fluid">
    <div class="row">

        
        <form class="rounded col-12" method="POST" action="/contatos/google" novalidate>
        <h1 class="rounded-top col-12" style="background: #4c793b7a;padding: 
                    2px;margin-bottom: 0px;margin-top: 10px; color:#32524f; ">
            Contatos do Google:
        </h1>
        {!! csrf_field() !!}
            <h6 class=" col-12" style="background: #5152517a;padding: 
                    2px;margin-bottom: 0px; color:#243a38;">
                Selecione os Contatos a serem adionados:
                <br>
                <button class="btn btn-primary" type="submit">Salvar</button>
                <button class="btn btn-warning btnTroca" type="buttom">Trocar Usuário</button>
                <button class="btn btn-danger btnCancelar" type="buttom">Cancelar</button>
            </h6>

            <table class="table table-bordered table-striped table-hover category-table">
                <thead class="thead-dark">
                    <tr>
                        <th class="textCenter">
                            <input id="selectAllImportados" type="checkbox">
                        </th>
                        <th class="textCenter">
                            Nome:
                        </th>
                        <th class="textCenter">
                            Sobrenome:
                        </th>
                        <th class="textCenter">
                            telefone:
                        </th>
                        <th class="textCenter">
                            email:
                        </th>
                    </tr>
                </thead>
                @foreach($contatos as $contact)
                <tbody class="background-contatos">
                    <tr class="tabela">
                        <td>
                            <input class="check" type="checkbox" onfocus="checkbox();">
                        </td>
                        <td class="textCenter">
                            <input type="text" class="yourName col-12 rounded" name="Nome[]" value="{{ $contact['name'] }}" disabled>
                        </td>
                        <td class="textCenter">
                            <input type="text" class="yourLastName col-12 rounded" name="SobreNome[]" value=" {{$contact['lastname']}}" disabled>
                        </td>
                        <td class="textCenter">

                            <input type="text" class="yourTel rounded" name="Tel[]" value=" {{$contact['tel']}}" disabled>

                        </td>
                        <td class="textCenter">
                            <input class=" yourEmail col-12 rounded" name="Email[]" type="text" value="{{$contact['email']}}" disabled>
                        </td>
                    </tr>

                </tbody>
                @endforeach

            </table>
        </form>
    </div>
</div>




<script>
    $(document).on('click', '#btnAddContatos', function(e) {

    });
</script>

<script>
    function checkbox() {
        enable_cb();
        $(".check").click(enable_cb);
    };

    function enable_cb() {

        var nameInput = $(this).closest('tr.tabela').find('input.yourName');
        var lastName = $(this).closest('tr.tabela').find('input.yourLastName');
        var tel = $(this).closest('tr.tabela').find('input.yourTel');
        var email = $(this).closest('tr.tabela').find('input.yourEmail');

        if ($(this).prop('checked')) {
            nameInput.removeAttr("disabled");
            lastName.removeAttr("disabled");
            tel.removeAttr("disabled");
            email.removeAttr("disabled");

        } else {
            nameInput.attr("disabled", true);
            lastName.attr("disabled", true);
            tel.attr("disabled", true);
            email.attr("disabled", true);
        }
    };
</script>
<script>
    $('button.btnTroca').on('click', function(e) {
        e.preventDefault();
        console.log('teste');   
        document.location.href = "https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://agendaeduardo.com/contact/import/google"; 
        console.log('a');  
    });
</script>
<script>
    $('button.btnCancelar').on('click', function(e) {
        e.preventDefault();
        console.log('teste');   
        document.location.href = "https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://agendaeduardo.com/contatos"; 
        console.log('a');  
    });
</script>


@stop

resources/views/paginas/editEvent.blade.php
@extends('layouts.app')

@section('content')
<div class="container" >
    <div class="card card-primary">
        <div class="card-heading">
            {!! Form::open(['route' => ['events.update', $event->id ],'id'=>'form','method' => 'PATCH', 'class' => 'contato-needs-validation rounded']) !!}
            {!! csrf_field() !!}
            @include('flash')
            <div class="row" style="margin: 0px;">
                <div class="col-4">
                    <div class="form-group">
                        <label for="event_name"> Nome do Evento:</label>
                        <!-- {!!Form::label('event_name', 'Nome do Evento:')!!} -->
                        <form name="form" id="register_form">
                            <div>
                                {!!Form::text('event_name', $event->event_name, ['class' => 'form-control', 'placeholder'=>'Evento']) !!}
                                {!! $errors->first('event_name', '<p class="alert alert-danger">:message</p>')!!}
                            </div>
                    </div>
                </div>

                <div class="col-4">
                    <div class="form-group">
                        <label for="start_date"> Data Início</label>
                        <!-- {!!Form::label('start_date', 'Data de início:')!!} -->
                        <!-- 2019/08/25 12:20 -->
                        <div>
                            <!-- <input type="datetime-local" class="form-control"  name="start_date"> -->
                            {!!Form::input('dateTime-local','start_date', date('Y-m-d\TH:i', strtotime($event->start_date)), ['class' => 'form-control']) !!}
                            {!! $errors->first('start_date', '<p class="alert alert-danger">:message</p>')!!}
                        </div>
                    </div>
                </div>

                <div class="col-4">
                    <div class="form-group">
                        <label for="end_date"> Data Final:</label>
                        <!-- {!!Form::label('end_date', 'data do Término:')!!} -->
                        <div>
                            {!!Form::input('dateTime-local','end_date', date('Y-m-d\TH:i', strtotime($event->end_date)), ['class' => 'form-control']) !!}
                            <!-- Form::time('time', \Carbon\Carbon::now()->timezone('Europe/Brussels')->format('H:i:s'),['class' => 'form-control']) -->
                            {!! $errors->first('end_date', '<p class="alert alert-danger">:message</p>')!!}
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary add-event" value="" id="add-event">Alterar Evento</button>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

@stop

resources/views/paginas/pesquisa.blade.php
@extends('layouts.app')


@section('content')

<div class="col-12">
    <div class="row">
        <div class="col-12">
            {!! csrf_field() !!}
            @include('flash')
            <h1 class="rounded-top" style="background: #504f4f54;padding: 
                    2px;margin-bottom: 0px;margin-top: 10px;color: #000;">
                Resultados de pesquisa para: #{{$search}}
            </h1>

            <table class="table table-bordered table-striped table-hover category-table">
                <thead class="thead-dark">
                    <tr>
                        <th class="textCenter col-10">
                            Valor:
                        </th>
                        <th class="textCenter col-2">

                            <div class="dropdown col-2">
                                <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Tipo
                                </a>

                                <div class="dropdown-menu col-2" aria-labelledby="dropdownMenuLink">
                                    <div class="dropdown-item">
                                        <input id="selectAll" type="checkbox" checked> TODOS
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkContato" onfocus="checkbox();" checked> CONTATO
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkEmail" onfocus="checkbox();" checked> EMAIL
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkTelefone" onfocus="checkbox();" checked> TELEFONE
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkCpf" onfocus="checkbox();" checked> CPF
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkEndereco" onfocus="checkbox();" checked> ENDEREÇO
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkEvento" onfocus="checkbox();" checked> EVENTO
                                    </div>
                                    <div class="dropdown-item">
                                        <input class="check" type="checkbox" id="checkCategoria" onfocus="checkbox();" checked> CATEGORIA
                                    </div>
                                </div>
                            </div>
                        </th>
                    </tr>
                </thead>
                @foreach($resultadoFinalContatos as $contact)
                <tbody class="background-contatos TabelaContato">
                    <tr class="btnDelete" id="{{$contact->id}}" data-id="{{$contact->id}}">
                        <td class="textCenter">
                            <a href="{{route('contato.edit',$contact->id)}}">
                                <p>{{ $contact->name }}
                                    <span style="font-size: 14px"> {{ $contact->last_name }}</span>
                                </p>
                            </a>
                        </td>
                        <td>
                            CONTATO
                        </td>
                    </tr>
                </tbody>
                @endforeach
                @foreach($resultadoFinalEmail as $email)
                <tbody class="background-emails TabelaEmail">
                    <tr class="btnDelete" id="{{$email->id}}" data-id="{{$email->id}}">
                        <td class="textCenter">
                            <a href="{{route('contato.edit',$email->contato_id)}}">
                                <p>
                                    {{ $email->email }}
                                </p>
                            </a>
                        </td>
                        <td>
                            EMAIL
                        </td>
                    </tr>
                </tbody>
                @endforeach
                @foreach($resultadoFinalTel as $tel)
                <tbody class="background-tels TabelaTel">
                    <tr class="btnDelete" id="{{$tel->id}}" data-id="{{$tel->id}}">
                        <td class="textCenter">
                            <a href="{{route('contato.edit',$tel->contato_id)}}">
                                <p>
                                    {{ $tel->tel }}
                                </p>
                            </a>
                        </td>
                        <td>
                            TELEFONE
                        </td>
                    </tr>
                </tbody>
                @endforeach
                @foreach($resultadoFinalCpf as $cpf)
                <tbody class="background-cpfs TabelaCpf">
                    <tr class="btnDelete" id="{{$cpf->id}}" data-id="{{$cpf->id}}">
                        <td class="textCenter">
                            <a href="{{route('contato.edit',$cpf->contato_id)}}">
                                <p>
                                    {{ $cpf->cpf }}
                                </p>
                            </a>
                        </td>
                        <td>
                            CPF
                        </td>
                    </tr>
                </tbody>
                @endforeach
                @foreach($resultadoFinalAddress as $address)
                <tbody class="background-endereco TabelaEndereco">
                    <tr class="btnDelete" id="{{$address->id}}" data-id="{{$address->id}}">
                        <td class="textCenter">
                            <a href="{{route('contato.edit',$address->contato_id)}}">
                                <p>
                                    {{ $address->city }}-{{$address->state}}- {{ $address->neighborhood }}- {{ $address->street }}- Nº:{{ $address->number }}- CEP: {{ $address->cep }}.
                                </p>
                            </a>
                        </td>
                        <td>
                            ENDEREÇO
                        </td>
                    </tr>
                </tbody>
                @endforeach
                @foreach($resultadoEventos as $event)
                <tbody class="background-evento TabelaEvento">
                    <tr class="btnDelete" id="{{$event->id}}" data-id="{{$event->id}}">
                        <td class="textCenter">
                            <a href="{{route('events.edit',$event->id)}}">
                                <p>
                                    Evento: {{ $event->event_name }}-> Início: {{ $event->start_date }}H -> Término {{$event->end_date}}H;
                                </p>
                            </a>
                        </td>
                        <td>
                            EVENTO
                        </td>
                    </tr>
                </tbody>
                @endforeach
                @foreach($resultadoCategories as $category)
                <tbody class="background-contato-cetegoria TabelaCategoria">
                    <tr class="btnDelete" id="{{$category->id}}" data-id="{{$category->id}}">
                        <td class="textCenter">
                            <a href="{{route('pesquisaCategoria',$category->category)}}">
                                <p>
                                    {{ $category->category }}
                                </p>
                            </a>
                        </td>
                        <td>
                            CATEGORIA
                        </td>
                    </tr>
                </tbody>
                @endforeach
                
            </table>
            
        </div>
    </div>
</div>

<script>
    $('#selectAll').click(function() {

        if ($(this).prop('checked')) {
            $('.check').prop('checked', true);
            $('.background-contatos').show();
            $('.background-emails').show();
            $('.background-tels').show();
            $('.background-cpfs').show();
            $('.background-evento').show();            
            $('.background-endereco').show();
            $('.background-contato-cetegoria').show();            
        } else {
            $('.check').prop('checked', false);
            $('.background-contatos').hide();
            $('.background-emails').hide();
            $('.background-tels').hide();
            $('.background-cpfs').hide();
            $('.background-evento').hide();
            $('.background-endereco').hide();
            $('.background-contato-cetegoria').hide();
        }
    });
</script>
<script>
    $('#checkContato').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaContato').show();
        } else {
            $('.TabelaContato').hide();
        }
    });
</script>
<script>
    $('#checkEmail').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaEmail').show();
        } else {
            $('.TabelaEmail').hide();
        }
    });
</script>
<script>
    $('#checkTelefone').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaTel').show();
        } else {
            $('.TabelaTel').hide();
        }
    });
</script>
<script>
    $('#checkCpf').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaCpf').show();
        } else {
            $('.TabelaCpf').hide();
        }
    });
</script>
<script>
    $('#checkEndereco').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaEndereco').show();
        } else {
            $('.TabelaEndereco').hide();
        }
    });
</script>
<script>
    $('#checkEvento').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaEvento').show();
        } else {
            $('.TabelaEvento').hide();
        }
    });
</script>
<script>
    $('#checkCategoria').click(function() {
        if ($(this).prop('checked')) {
            $('.TabelaCategoria').show();
        } else {
            $('.TabelaCategoria').hide();
        }
    });
</script>

@stop

resources/views/paginas/pesquisaCategoria.blade.php
@extends('layouts.app')


@section('content')

<div class="container-fluid">
    <div class="row">
            <div class="col-12 ">
                {!! csrf_field() !!}
                @include('flash')
                <h1 class="rounded-top" style="background: #504f4f54;padding: 
                    2px;margin-bottom: 0px;margin-top: 10px;color: #000;">
                    Contatos: #{{$categoria->category}}
                </h1>
                
                    <table class="table table-bordered table-striped table-hover category-table">
                        <thead class="thead-dark">
                            <tr>
                                <th class="textCenter">
                                    Nome:
                                </th>
                                <th class="textCenter">
                                    Telefone:
                                </th>
                                <th class="textCenter">
                                    Excluir:
                                </th>
                            </tr>
                        </thead>
                        @foreach($contacts as $contact)
                            <tbody class="background-contato-cetegoria">
                                <tr class="btnDelete" id="{{$contact->id}}" data-id="{{$contact->id}}">
                                        <td class="textCenter">
                                            <a class="nav-link contato-link link-contato" href="{{route('contato.edit',$contact->id)}}">
                                                <p>{{ $contact->name }}
                                                    <span style="font-size: 14px"> {{ $contact->last_name }}</span>  
                                                </p> 
                                            </a>
                                        </td>
                                        <td class="textCenter" style="font-size: 22px;">
                                            @if(is_null($contact->tels->first()))
                                                ----
                                            @else
                                                {{ $contact->tels->first()->tel}}
                                            @endif
                                        </td>
                                    
                                    <td class="textCenter">
                                        <!-- <button class="btn btn-danger delete-contact" value="{{$contact->id}}">Deletar</button>  -->
                                        <button type="button" class="btn btn-danger-tabela btnDelete" data-toggle="modal" data-id="" data-target="#myModal">Delete</button>
                                    </td>
                                
                                </tr>
                            </tbody>
                        @endforeach
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Deletar?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        tem certeza que deseja enviar contato para lixeira?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>                                            
                                        <!-- <button class="btn btn-danger delete-contact" value="">Deletar</button>  -->
                                        <button type="button" class="btn btn-danger delete-contact" value="" id="delete-btn">Deletar</button>   
                                    </div>
                                </div>
                            </div>
                        </div>
                </table>
            </div> 
        </div>
    </div>
</div>  



<script>

$('button.btnDelete').on('click', function (e) {
    e.preventDefault();
    console.log('teste');
    var idContato = $(this).closest('tr').data('id');
    console.log(idContato);
    
    $('.delete-contact').click(function () {
        var id = idContato;
        console.log(id);
        console.log('teste');   
        $.ajax({
            type:"POST",
            url:'/contato/' + id,
            data:{_method: 'delete', _token : "{{ csrf_token() }}"},
            success: function (data) {
                console.log(data);
                $("#"+id).remove();
                $('#myModal').modal('hide');
                
            },
            error: function (data) {
                console.log('Error:', data);
            }

        });

    });
});


</script>
@stop

resources/views/paginas/primeira.blade.php
@extends('layouts.app')

@section('content')

<div class=" primeira__pag"></div>
@stop

resources/views/paginas/unauthorized.blade.php
Unauthorized